### ISSUE TITLE
Fix security vulnerability in dependencies

### ISSUE THREAD

**Issue by altany** [altany/tany4#3]
There seems to be a potential security vulnerability in one of the dependencies.
The dependency hapijs / hoek (2.16.3) which is defined in package-lock.json has known security vulnerabilities and should be updated.

Good luck and happy hactoberfest :)

**Comment by cbsorrilha** [comment]
I'll do it :smile:

**Comment by altany** [comment]
Awesome! Thank you and good luck!

**Comment by cbsorrilha** [comment]
request-http-cache already has an issue to update de insecure dependencies.

**Comment by altany** [comment]
Thank you for looking into this!

**Comment by altany** [comment]
This seems to be a problem with `request-http-cache`. There is already[ an issue in there repo](https://github.com/gitterHQ/request-http-cache/issues/10).
