### ISSUE TITLE
Saturate icons on hover

### ISSUE THREAD

**Issue by altany** [altany/tany4#4]
The page under tany4.com/social contains several icomoon icons. I would like to make the page more user friendly by increasing the colour saturation of the icons on hover.

So, ideally, the icons would load on something like 60% saturation and on hover set it to 100%.

Feel free to set a different initial saturation value per icon if you think it looks better, or even changing any other filter, not just saturation. Whatever works :)

Good luck and happy hacktoberfest!

**Comment by parulgupta26** [comment]
I can pick this up

**Comment by altany** [comment]
Awesome! Good luck :)

**Comment by parulgupta26** [comment]
> Awesome! Good luck :)
PR - 
https://github.com/altany/tany4/pull/6
